### ISSUE TITLE
README has incorrect instructions for project set-up

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/planner#100]
### What did you expect to happen?

I attempted to set up a local copy of the Planner, and I followed the Set-up instructions in the Readme. I cloned the project, with Node.js and NPM installed (as the only listed requirements) and ran `npm start`.

### What happened?

When I attempted to set up a local copy of the planner to test changes, I followed the instructions in the Readme only to find that the project appears to require Next.js. When I executed `npm start`, I was presented with errors that suggest Next wasn't installed. Even after installing it, I get the following error when running:

```
Error: Could not find a production build in the '/Users/.../Nebula/planner/.next' directory. Try building your app with 'next build' before starting the production server.
```

I'm sure I'm missing some easy setup, but the necessary steps should be in the Readme as well if needed.

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WillieCubed** [comment]
It appears the README is inaccurate: Next.js projects use `npm run dev` by default. Use that instead `npm start` is used when running a production deployment.

**Comment by Jake3231** [comment]
Using `npm run dev` did help. Though I now run into:
```
Error storing data ReferenceError: window is not defined
    at /Users/jake/Documents/Nebula/planner/node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.js:81:7
    at /Users/jake/Documents/Nebula/planner/node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.js:37:21
    at new Promise (<anonymous>)
    at createPromise (/Users/jake/Documents/Nebula/planner/node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.js:35:10)
    at Function.setItem (/Users/jake/Documents/Nebula/planner/node_modules/@react-native-async-storage/async-storage/lib/commonjs/AsyncStorage.js:80:12)
    at writeStagedState (/Users/jake/Documents/Nebula/planner/node_modules/redux-persist/lib/createPersistoid.js:98:28)
    at Timeout.processNextKey [as _onTimeout] (/Users/jake/Documents/Nebula/planner/node_modules/redux-persist/lib/createPersistoid.js:87:7)
```
Could this be something else that I'd need to set up?

**Comment by WillieCubed** [comment]
Just to follow up, it appears this project may have an unresolved bug that one of the maintainers will have to address.

**Comment by ZzRanger** [comment]
#80 addresses the bug mentioned above.
