### ISSUE TITLE
[Bug]: Dashboard does not scale correctly on displays with less horizontal space

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/planner#106]
### What did you expect to happen?

When switching to a device with less horizontal resolution, the dashboard should reorganize listed degree plans so that cleanly appear on mobile (or any small) displays. One way to approach this could be to set degree plans to switch to a vertical list on mobile, for example.

### What happened?

The Planner dashboard currently does not properly scale to displays with a lower width, such as most mobile devices. As the device width decreases, the listed degree plans begin to overlap.

https://user-images.githubusercontent.com/13911970/155896960-cf80704e-cf8c-400f-85c5-632bb6c1f8b7.mov

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WillieCubed** [comment]
Ha, I should really be removed from the CODEOWNERS so I stop getting assigned to these. 😆
