### ISSUE TITLE
[Feature Request] Revamp Landing Page

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#109]
# Overview

Currently, the landing page on Planner looks a bit basic. It was supposed to be temporary and was meant to be replaced with a more animated and eye-popping page. Having a well-designed landing page is important in order to leave a good first impression on the user.

# Proposal

Below is a mockup of what the landing page should ideally look like.

![Login Flowlanding](https://user-images.githubusercontent.com/47403443/156493903-417fd77a-2cd0-4ed3-b227-8741ee134648.png)

Animating the page (i.e. adding a typewriter effect on the text, putting videos in the background) would help the page come to life.

# Supplemental Information

https://www.figma.com/file/cycV0bxP6vTJJYUONFoBr0/Planner-Mockups?node-id=26840%3A43579 contains other variations of the page.

**Comment by lokeshyerneni** [comment]
I got it

**Comment by WillieCubed** [comment]
For something as important as the landing page, I'm going to ask that you have one of the designers for Planner finalize the mock-up after obtaining feedback from others and after your product designer outlines the requirements of the landing page. No implementation should begin until then.

**Comment by ZzRanger** [comment]
I was under the impression that the landing page was done given the state of the mockups in the Figma file. However, we can do the things you mentioned before we start implementing.

**Comment by ZzRanger** [comment]
Refer to #96 for updated information on the Landing Page.
