### ISSUE TITLE
[Feature Request]: Add Protected Routes

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#110]
# Overview

There should be certain routes on Planner that are restricted depending on the state of the application (i.e. if a user is properly authenticated or if a certain degree plan exists for 'app/plans/[degree plan id]'). Users that attempt to access protected routes should then be redirected to another route (i.e. the landing page).

# Proposal

1. Routes that start with '/app' should require the user to be authenticated in order to access.
 - If this condition is not satisfied, redirect the user to the landing page.

2. The route '/app/plans/[planId]' should require a valid plan to exist.
- If this condition is not satisfied, redirect the user to '/app/plans'

If anyone has any suggestions or ways to improve this, please put your thoughts down below.

**Comment by WillieCubed** [comment]
I will note that the intent with Planner was to not require authentication by default and to use the concept of [progressive enhancement](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement) to enable featured based on auth state, so the protected routes should reflect that.

**Comment by ZzRanger** [comment]
Yeah, that was the intent of the protected routes. 

However, I think even "anonymous" users should still have to go through the landing page and be given a "guest" user identity before being able to use the other features of Planner. The reasoning for this is that it wouldn't make sense for a first-time user to access the settings page (via route '/app/settings') without first going through the landing page. 

Please let me know what you're thoughts are on this.
