### ISSUE TITLE
[Feature Request] Add Announcement Bar w/ Feedback Form

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#114]
# Overview

There should be a simple and easy way for users to give feedback on Planner.

# Proposal

1. Create a Google Form to collect feedback from users (specifically feature request & bugs).
2. The Form will automatically create a GitHub issue when submitted.
3. The link to the form will be in an announcement bar on Planner. 

This approach would help non-CS users give feedback and it'll make it easy for us to organize the information and take action.

**Comment by WillieCubed** [comment]
For the form integration, @ConnorSimply can address this as someone in charge of Project Nebula's more internal infrastructure. Given that this is something that is replicable across multiple projects, I would rather have Connor build a solution that can be generalized to give feedback for all of Project Nebula's products than rely on individual products which may build non-standardized solutions.

**Comment by ZzRanger** [comment]
Sounds good.

**Comment by ZzRanger** [comment]
**Steps to Implement**

Design
1. Design an announcement bar 

Engineering
1. Implement said announcement bar

Product
1. Come up with questions to ask for feedback & make Google Form

Engineering
1. Add form link to announcement bar
