### ISSUE TITLE
[Feature Request] Store User Transfer Credits

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#118]
# Overview

Per #107, there should be a way for users to enter any transfer credits that they have so that they can apply them in their degree plan.

# Proposal

Create a Transfer Credit tool to enter any transfer credits that the user has. This tool will have the following functionality:

- user will enter the credit type (i.e. AP, CLEP, Transfer) and score if applicable
- this information will then be stored as part of the user's personal data

This information will then be used inside New Plan Creation Flow before the degree plan generation, and the degree planning tool itself.

# Supplementary Information

The same person/s who work on this should work on #156 .

**Comment by ZzRanger** [comment]
We will be adding this functionality to this screen: 
![Image](https://user-images.githubusercontent.com/47403443/189797838-061d018d-6ec4-4a10-bba2-d606fa288933.png)

**Comment by innub** [comment]
Hey, 

I was assigned to 156. Can I be assigned to this as well.

Thanks

**Comment by ZzRanger** [comment]
Close from #216
