### ISSUE TITLE
[Feature Request] Add Loading Page 

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#121]
# Overview

There is currently isn't a design for a fallback page that appears while data is loading for a certain page.

# Proposal

Design and implement a loading page to display whenever data is loading for a certain page (i.e. after user authenticated)

**Comment by aanos-m** [comment]
I will do it

**Comment by WillieCubed** [comment]
Whoops, just ignore that. I wasn't paying attention and thought this was the UTDNebula/survival-guide repo.
