### ISSUE TITLE
[Feature Request] Parse Credit History From Transcript

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#123]
# Overview

The current way for a user to add past courses is by manually entering them via the Course Audit or Transfer Credit tool. However, it would be really cool if a user could simply upload an unofficial transcript obtained via Galaxy to add their past courses.

# Proposal

In the section with the Course Audit and Transfer Credit tool, provide the user with the option to upload their transcript to auto-populate past credits taken.

**Comment by cheblankenshipUTD** [comment]
I would like to pick up this task.

**Comment by ZzRanger** [comment]
**Steps to Implement**
1. Parse PDF in a node.js runtime. What you can do to is get a sample transcript (this can be found in UTD Orion > My Academics > My Academic Requirements) and try to parse it. [pdf-parse](https://gitlab.com/autokent/pdf-parse ) seems like a good library, but feel free to try other ones out.
2. Once that's done, move this logic into a node.js api route and create a sample page (i.e. pages/test.tsx) with an "Upload pdf" form for the user. This [tutorial](https://towardsdev.com/upload-files-with-nextjs-fetch-api-routes-typescript-8150f9fa2332) seems like a good place to start.
3. We will handle integrating into the UI in a separate issue, but that shouldn't be too bad as long as this core logic is working.

**Comment by ZzRanger** [comment]
We will also need Product team to weigh in on finding the best place to put this piece of functionality.

**Comment by ZzRanger** [comment]
Resolved from #248
