### ISSUE TITLE
[Feature Request] Store User Course Credits

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#156]
# Overview

There should be a way for users to enter any UTD credits that they have so that they can appear in their degree plan as "taken".

# Proposal

Create an Add Credits tool to enter any UTD credits that the user has. This tool will implement the functionality in the image below:

![image](https://user-images.githubusercontent.com/47403443/189798314-41103afb-dc7e-4d2b-98b9-a0725b73d883.png)

#Supplementary Information

The same person/s who work on this should also work on #118 .

**Comment by innub** [comment]
Hey @ZzRanger,

Could I be assigned to this and 118?

Thanks

**Comment by ZzRanger** [comment]
Can you comment on #118 so I can assign?

**Comment by ZzRanger** [comment]
Close via #216
