### ISSUE TITLE
[Bug]: Clicking on the first plan takes a long time to load

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#168]
### What did you expect to happen?

I expect the degree planning tool to immediately load after clicking on a plan.

### What happened?

![ezgif-1-01d169a597](https://user-images.githubusercontent.com/47403443/189971926-3e53db40-161d-4bc5-8f1e-875fcec5f95c.gif)

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by innub** [comment]
For some reason the response is 4MB compressed and 40MB decompressed. 
![image](https://user-images.githubusercontent.com/76929931/190060984-e91098f4-155a-40d7-afa7-930f8e5278b4.png)

The production builds are completely fine. I ran [this analyzer](https://www.npmjs.com/package/@next/bundle-analyzer) on the build, and the bundle size is completely normal. Compressed bundle size on the server is about 100KB and on the client is 500KB.
 
The issue seems to be that MUI isn't being tree-shaken for some reason (see [.next/trace](https://gist.githubusercontent.com/innub/aa583723ff3a7b05d2b0e8564bde97d3/raw/51380e50c30865b436511c6ec9e9e54b19999589/trace)). Seems there are many top-level imports for @mui/material and @mui/icons-material throughout the code, so that's probably why.

**Comment by ZzRanger** [comment]
Nice analysis! This is something we would like to optimize sometime in the future. If you are interested in working on this let me know and I can assign this to you.

**Comment by innub** [comment]
hey @ZzRanger,

I wouldn't mind working on this issue.

If it is an issue of top-level imports, I'm not really sure why it doesn't occur in production build. I would imagine tree-shaking would be the same for production and development, but I honestly don't know what the default configuration is. Maybe the production build is just as unoptimized but the compression hides any noticeable size? I'll look into it.

**Comment by ZzRanger** [comment]
Per discussion at 9/20 meeting, we'll be tabling this issue for now.

**Comment by ZzRanger** [comment]
Linking #118 #156 and by extension #216, as we can look to optimize loading time of Credits page as well. I have some intuition on how to do it (potentially load components after initial page load through some useEffect magic) but will need further discussion.

**Comment by innub** [comment]
So after taking a good look at the bundle size, there are two culprits to the large bundle size.
![image](https://user-images.githubusercontent.com/76929931/196043651-8eb6c270-8349-43dc-ab75-4b9d08bbce78.png)

Redux looks really big, but it's actually its usage of Firebase which is discussed later.

## courses.json
This file is really huge. We could get rid of it and use Next's API routes or a Firebase cloud function instead. Not sure if the latency of the request is better than loading it in the bundle, but we could give it a show.

## Mui

After a good amount digging, I discovered that Next supports transforming imports via SWC, which would allow Webpack to properly tree shake MUI.

However, we are currently using v12.1 and import transform was added afterwards [see here](https://github.com/vercel/next.js/releases/tag/v12.1.1-canary.18). This would require us to update to [v12.2.6](https://nextjs.org/blog/next-12-2), which does NOT include breaking changes for us. 

Upgrading to v12.2.6 and taking advantage of import modularization allows us to go from compiling 11k to 1k modules, which is noticeably faster in the development environment and marginally faster in production.

**With v12.2.6 import modularization:**
![image](https://user-images.githubusercontent.com/76929931/196043445-3f9cc3f0-b99a-451a-a500-7b440d09da64.png)

**Without import modularization:**
![image](https://user-images.githubusercontent.com/76929931/196043355-23c5b99a-5cc9-4f68-ad50-35c61a489f8e.png)

## Firebase
Firebase is an absolute tank (113KB + unknown size when used in Redux) and is loaded on every single page. Unfortunately, we are using v8.4.1, while tree shaking in only supported v9+ (see here)[https://firebase.google.com/support/release-notes/js#version_900_-_august_25_2021}.

**Comment by ZzRanger** [comment]
Nice work! 2020-courses.json was meant to be a temporary solution until the API goes live so we're planning on removing it anyway once we integrate Nebula API. 

Regarding MUI & Firebase, I'm cool with upgrading Next & Firebase sometime after beta launch.

**Comment by sarthak22gaur** [comment]
There are a lot of perf improvements that can be done in this.

1.  We can get away with almost 90% of the redux store by using SSR and caching query data.
2.  The courses list can be cached as well quite easily
3.  Defining better suspense boundaries will greatly increase the UI/UX experience in terms of loading times.
