### ISSUE TITLE
[Feature Request] Course Validation

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#169]
# Overview

This is what the user sees when using the degree planning tool to build your schedule. There currently is not a way to validate whether the student has met all the prereqs needed to take a certain class at a certain semester. This makes it difficult for students to know whether or not their degree plans are valid.
<img width="1433" alt="Screen Shot 2022-09-13 at 12 32 00 PM" src="https://user-images.githubusercontent.com/47403443/189973204-2d8c7246-e299-42d5-bc30-a2f360acebb0.png">

# Proposal

Given a degree plan, mark the courses that the user is ineligible to take due to unmet pre/corequisites. The end goal is to have something like this:

<img width="560" alt="Screen Shot 2022-09-13 at 11 07 34 PM" src="https://user-images.githubusercontent.com/47403443/190057306-5c7e9eed-7709-4480-8486-17f7e62138c9.png">

## Supplementary Information

If you are interested in working on this, comment down below and I will give more context on how to proceed.

**Comment by ez314** [comment]
This is for prereqs, but also interested in doing this for graduation requirements.

**Comment by ez314** [comment]
All progress here: https://github.com/ez314/Degree-Validator/blob/f3196ce00408046e81fe9550550da32faf3b7ee9/maxflow.py#L164

For now, planning on hosting on separate backend or within Firebase Functions
