### ISSUE TITLE
[Bug]: Continue as Guest shows profile briefly before taking to walkthrough

### ISSUE THREAD

**Issue by JCGarzaa** [UTDNebula/planner#172]
### What did you expect to happen?

When clicking continue as guest, I assume that it is supposed to take you to the walkthrough right away where you enter information. However, there is a moment before where the user sees a glimpse of the profile screen. 

### What happened?

After clicking "continue as guest", there is a moment when the screen shows a profile screen that the user would see after entering their information.

https://user-images.githubusercontent.com/83436163/190197710-2a7b4861-fd2b-455d-917e-acd607fdefbc.mp4

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Devan-Kerman** [comment]
I'll work on this

**Comment by Devan-Kerman** [comment]
I'll work on this
