### ISSUE TITLE
[Feature Request] Taking into Account Course Difficulty When Generating Degree Plans

### ISSUE THREAD

**Issue by JCGarzaa** [UTDNebula/planner#173]
# Overview

In cooperation with Trends, Planner could create degree plans that take into account/visualize course difficulty. A star rating could be shown under each course to show relative difficulty in order to assist the user further when deciding which classes to take at certain times. Further down the line, it would be nice if when Planner generates a degree plan, it adds courses in a way that the average difficulty of the semester is relatively close to each other. This would allow users who want to add a minor/extra courses later on to see the best opportunity to take them.

# Proposal

First would be working with trends to track a relative difficulty for a course (using grade distribution, professor grades, etc.) Then assigning a value to each course would be necessary. Following that, displaying the difficulty would be a start and then taking an average difficulty for a semester and displaying to the user would also be helpful. Later implementations can begin messing around with the generation of degree plans in a way that the remaining courses for someone is organized such that the difficulty is not outrageously different from semester to semester.

## Supplementary Information

Feel free to respond to this for more context.

**Comment by ZzRanger** [comment]
I will talk to Trends about the possibility of doing something like this. I'm not sure how feasible this will be this semester, but I think a feature like this would be great to have!
