### ISSUE TITLE
[Feature Request] Recommend Eligible Minors/Certificates

### ISSUE THREAD

**Issue by JCGarzaa** [UTDNebula/planner#174]
# Overview

Many students do not realize without extensive research that they may be fairly close to meeting requirements for a minor in a subject similar to their major (ex: Major is ME and close to minor in Math). This feature would prompt users when creating a plan/editing their current plan that you only need X amount of classes to complete the minor. With this, the user could click yes/no and if yes the courses would be automatically added to their current schedule.

# Proposal

Data needs to be generated to see required courses for each minor. The Planner needs to look at the completed courses of a user and determine how many classes would remain for minors similar to their major (could start with checking all available minors but then get reduced to similar ones based on past data for optimization). If there are a low number of classes remaining, prompt the user with a dialog on the side of the screen, similar to a chat notification, that they only need X amount of classes to complete the minor.  There then needs to be two clickable buttons that signify yes/no for adding the courses to their current degree plan. When clicking yes, the courses would add themselves to the current plan for future semesters. When doing this, it would want to possibly consider the amount of credits for each semester currently to try and ensure it doesn't exceed the credit limit. When clicking no, the message will simply dismiss. We would not want the same messages to repeat to the user so once they are dismissed, they will not be recommended for a period of time.

## Supplementary Information

I can provide more details if necessary. Feel free to respond to this.

**Comment by ZzRanger** [comment]
We will need to first get degree validation completed, as the logic for this would be very similar to the one for degree validation. Tabling this for now, but definitely want something like this implemented in the future

**Comment by ZzRanger** [comment]
Overkill for now I think. Def something to look for in the future though!
