### ISSUE TITLE
[Internal] useSearch Hook Should Be Generic and More

### ISSUE THREAD

**Issue by innub** [UTDNebula/planner#177]
## ``useSearch`` Hook Should Be Generic, Accept Result Size Constraints, Accept Initial Query, and Allow for Dynamic Filter Equality Function

**I would like to emphasize**
> Changing this hook will cause breaking changes in numerous places, but I feel like it would improve usability and allow us to avoid future headache.

### The main issue
Based on the current implementation, it seems like ``useSearch``'s main purpose is to serve as an unbiased wrapper around data retrieval/filtering. I assume that's why the ``getData`` function is a parameter and not hard-coded.

The main issue I have with its current implementation is that the filter equality function is also hard-coded which basically limits what kind of data you can pass in, and how it is compared.

### Making it generic
This is just for type safety. 

Obviously for ``useSearch`` to work we must make 2 assumptions:
- getData must return a Promise
- the data must be an array

Currently, it is not type safe.

### The other parameters
- initialQuery so we can rid of ``useEffect(()=>updateQuery('')))`` which I find odd that it's being written outside of the hook!
- constraints[2] which would not only allow for future pagination but also just limit the size without writing the logic elsewhere  

## A working implementation looks something like:

```Typescript
interface SearchParams<T, K> {
  getData: () => Promise<T[]>;
  chips?: any[];
  initialQuery: K;
  filterFn: (element: T, query: K) => boolean;
  constraints?: [number, number];
}

interface SearchReturn<T, K> {
  results: T[];
  getResults: () => T[];
  updateQuery: (query: K) => void;
}

/**
 * This function performs search & returns relevant data
 * */
const useSearch1 = <T, K>({
  getData,
  initialQuery,
  filterFn,
  constraints = [0, 20],
  chips = [],
}: SearchParams<T, K>): SearchReturn<T, K> => {
  const [results, setResults] = React.useState<T[]>([]);

  const getResults = () => {
    return results;
  };

  React.useEffect(() => updateQuery(initialQuery), []);

  // TODO: Insert logc for filtering w/ chips
  // TODO: Update filtering code to deal with data from Neblua API
  const updateQuery = (query: K) => {
    getData()
      .then((data) =>
        data.filter((el) => filterFn(el, query)).slice(constraints[0], constraints[1]),
      )
      .then((data) => {
        setResults(data);
      })
      .catch((error) => {
        console.error('Could not update query', error);
      });
  };

  return { results, getResults, updateQuery };
};
```

Changing this hook will cause breaking changes in numerous places, but I feel like it would improve usability and allow us to avoid future headache.

**Comment by ZzRanger** [comment]
That logic makes sense to me. I agree having a generic useSearch would be helpful for querying courses, majors, etc. After a quick glance at the codebase it should be relatively straightforward to replace the current useSearch hook, and your working implementation looks good to me. Good job!

**Comment by NoWhere-2-Go** [comment]
I'd like to work on this too

**Comment by ZzRanger** [comment]
@NoWhere-2-Go made a follow up issue #188. Upon review of PR there isn't too much work left for this ticket. If you're still interested in working on it please comment on 188 so I can assign it to you!

**Comment by ZzRanger** [comment]
Close via #180
