### ISSUE TITLE
[Redesign] Credits Page

### ISSUE THREAD

**Issue by innub** [UTDNebula/planner#187]
# Redesign Credits Page

We agreed upon the following at the 9/20/22 design meeting
- It should be user responsibility to choose the correct UTD credit, even for transfer courses
- Credits should only have 2 pieces of information: the course code and whether they are transfer or not
- Credits list should only be one list where individual credits are flagged as transfer or not (as opposed to 2 lists)
- General consensus seemed to be that the 'add credit' and 'credit list' function of the credits page are equal in importance (both should be easily visible to user)

# NON-FINAL version of design 
![image](https://user-images.githubusercontent.com/76929931/191544427-e7e67203-70d1-4f70-942c-3f1656fac0d0.png)

## Points that were considered
- It doesn't fit with style of existing pages (ie. floating rectangles)
- If we remove the wavy background and floating rectangles there is too much whitespace and changing the background to a nonwhite doesn't help

# What we'd probably do 
- Just throw the form and list design onto the existing page and get rid of the floating rectangles

Related: #156 #118

Let me know if I misconstrued something from the meeting!

**Comment by innub** [comment]
## What it may look like with flags:

![image](https://user-images.githubusercontent.com/76929931/191554528-021d7af5-aabb-4fc7-9e92-dd8dec1b25ae.png)

**Comment by ZzRanger** [comment]
Yooo the flag for input & on existing credits looks 🔥 .
One thing we could consider is allowing the user to enter multiple credits in the search bar before clicking "Add Credit". Something like that might make the credit adding process more smooth.

**Comment by 1solomonwakhungu** [comment]
> # Redesign Credits Page
> We agreed upon the following at the 9/20/22 design meeting
> 
> * It should be user responsibility to choose the correct UTD credit, even for transfer courses
> * Credits should only have 2 pieces of information: the course code and whether they are transfer or not
> * Credits list should only be one list where individual credits are flagged as transfer or not (as opposed to 2 lists)
> * General consensus seemed to be that the 'add credit' and 'credit list' function of the credits page are equal in importance (both should be easily visible to user)
> 
> # NON-FINAL version of design
> ![image](https://user-images.githubusercontent.com/76929931/191544427-e7e67203-70d1-4f70-942c-3f1656fac0d0.png)
> 
> ## Points that were considered
> * It doesn't fit with style of existing pages (ie. floating rectangles)
> * If we remove the wavy background and floating rectangles there is too much whitespace and changing the background to a nonwhite doesn't help
> 
> # What we'd probably do
> * Just throw the form and list design onto the existing page and get rid of the floating rectangles
> 
> Related: #156 #118
> 
> Let me know if I misconstrued something from the meeting!

If there no way to access a user's current and past courses if they log in using their UTD credentials?

**Comment by 1solomonwakhungu** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/65043605/191648380-048e2cf1-aaa0-4c53-aab2-c6d1e867bb6a.png)

This is a redesign—added items to show the user their current credit hours. If the page doesn't have many features, a lot of the whitespace could have been used to portray more information to the user instead of filling the space with artwork.

I was also thinking of adding a context us icon at the bottom of the page. This would allow users to suggest new features right on the portal. 

Your design was good and the colors were not conflicting with each other. The font selection and size were also appropriate.

**Comment by ZzRanger** [comment]
I like this a lot! I think it's a really nice way of putting the credit adding functionality next to the list of courses. 

At the moment, we are not tracking professors and we would need another field on the left to end the semester they took the course in. What are your thoughts on having professors for Credits? I personally think it's a bit overkill since users will primarily be using this to build degree plans and not to choose class sections for each semester. However, if you feel differently please leave your thoughts below.

**Comment by ZzRanger** [comment]
I like the "Contact Us" idea. Please make an issue for that.

**Comment by 1solomonwakhungu** [comment]
> I like this a lot! I think it's a really nice way of putting the credit adding functionality next to the list of courses.
> 
> At the moment, we are not tracking professors and we would need another field on the left to end the semester they took the course in. What are your thoughts on having professors for Credits? I personally think it's a bit overkill since users will primarily be using this to build degree plans and not to choose class sections for each semester. However, if you feel differently please leave your thoughts below.

The information to include in the Course section can definitely be discussed. I just put the professor field there as a sample.

**Comment by innub** [comment]
@1solomonwakhungu,

I love the design! It's definitely superb to anything we've had so far.

Just a few small critiques and questions:
-  The orange checks on the Courses panel are unintuitive because there's no obvious functionality that has to do with selecting courses
- I don't think we should track professors for now
- I'm not really sure if the status is necessary but it would be a nice-to-have
- How do you feel about adding a filter-by widget between the "Courses" title and column titles?

Other than that, great design!

**Comment by 1solomonwakhungu** [comment]
I was thinking of adding a filter button. We can definitely remove the professor column. I will think more about the Course section. Will do a redesign and upload it later this week.

**Comment by ZzRanger** [comment]
Closed from #216
