### ISSUE TITLE
[Feature Request] Add Contact Us option on the Planner UI

### ISSUE THREAD

**Issue by 1solomonwakhungu** [UTDNebula/planner#190]
# Overview

The Planner portal is designed to help UTD students keep track of the credits they already took. Though, there are features on the Planner portal that students might want that have not yet been implemented. There needs to be a mechanism to take feedback from the user and notify the Planner team of requested changes. 

# Proposal

The solution is to include a contact icon at the bottom of the page for users to easily input their feedback to the Planner team. 

## Supplementary Information

Attached is the contact icon in the UI

![Web 1920 – 1](https://user-images.githubusercontent.com/65043605/191775779-916ddffb-894f-44e1-b289-26f798526569.png)

**Comment by ZzRanger** [comment]
We have thought about adding something like this in the past. I've personally envisioned putting something like this in an announcement banner that links to a Google Form. Any thoughts on the placement of the "Contact Us" icon?

<img width="1439" alt="Screen Shot 2022-09-25 at 7 30 14 PM" src="https://user-images.githubusercontent.com/47403443/192173033-2bcd4bda-0165-4b29-95b5-edfed9f3f3c6.png">
