### ISSUE TITLE
[Clarification] How to add unit tests for API route?

### ISSUE THREAD

**Issue by Spaceface16518** [UTDNebula/planner#223]
# Question

I am using Next.js API routes to implement a db query. I want to add unit tests to check simple test cases. Is there an established way to add unit tests within this repository? i.e. a specific testing framwork, tests directory, etc.

**Comment by Spaceface16518** [comment]
Specifically paging @ZzRanger. I could've asked this in a DM but I figured it was valuable for record/docs purposes.

**Comment by ZzRanger** [comment]
Thanks for making an issue. At the moment there is no precedent for adding unit tests in the repo. From skimming through the NextJS [doc](https://nextjs.org/docs/testing) we could use Jest for writing the unit tests for your use case. What do you think?

**Comment by ZzRanger** [comment]
Moved to discussion
