### ISSUE TITLE
[Feature Request] Add tooltips to certain buttons and/or icons

### ISSUE THREAD

**Issue by jolores4** [UTDNebula/planner#231]
![Screen Shot 2022-10-14 at 11 32 28 AM](https://user-images.githubusercontent.com/97186452/195896374-3a105036-18bc-442f-a9cb-be6e93f7617c.png)

In the above example, some users might become confused with the "75%" feature; consider adding a tooltip for clarification when the user hovers over the icon.

![Screen Shot 2022-10-14 at 11 35 47 AM](https://user-images.githubusercontent.com/97186452/195896924-e6fa3b3c-04bc-4372-bcdf-5f1a0dc531b0.png)

Same with these +/- buttons--need to clarify when the user hovers over the icon. (Does it add a new semester? Or a new credit/course?)

**Comment by ZzRanger** [comment]
### Action Items

**Product**
1. Make a list of buttons and/or icons to add tooltips for
2. Create descriptions for each tooltip
3. Question: do we want to have tooltip icons or just tooltips?

**Design**
1. Design a generic component for tooltip 
2. Design how the tooltip should appear on UI

**Engineering**
1. Create a generic Planner tooltip component
2. Add tooltips to all buttons/icons listed

**Comment by ZzRanger** [comment]
Will move this somewhere else besides an issue
