### ISSUE TITLE
[Feature Request] Export/import options (file specifications)

### ISSUE THREAD

**Issue by Afsartech** [UTDNebula/planner#233]
<img width="270" alt="Screen Shot 2022-10-14 at 12 16 15 PM" src="https://user-images.githubusercontent.com/64441916/195913770-f31db1eb-9702-4c0b-84a5-3d8795542fef.png">

Above is our current export/import options and when you click the buttons you j get the file and thats it.
I feel like there should be more options as that allows for more free use of our applications. Some examples are below.
<img width="554" alt="Screen Shot 2022-10-14 at 1 10 23 PM" src="https://user-images.githubusercontent.com/64441916/195914059-5dcce478-ec1a-4393-b05e-842ca1a53685.png">

By allowing an option to export which file they want and what quality it makes it easier for the user to share there planner with other students or even course advisors. 

Another example below allows the user to be notified what files are acceptable and prompts them to select a file from their machine. 
<img width="549" alt="Screen Shot 2022-10-14 at 1 13 51 PM" src="https://user-images.githubusercontent.com/64441916/195914537-35423b34-924f-4f34-a89f-b14199dde280.png">

**Comment by ZzRanger** [comment]
**Steps to Implement**

Product
1. Come up with file types for import and export
2. Finalize location of feature on application

Design
1. Create design for this component

Engineering
1. Create API routes for each file import & export

**Comment by ZzRanger** [comment]
Should we support being able to import or export multiple plans at once?
