### ISSUE TITLE
[Feature Request]User Settings

### ISSUE THREAD

**Issue by cpshawn** [UTDNebula/planner#235]
A separate Settings page for:

-Different themes (mostly color skins)

-Course listing preferences (by professor name, professor rating, average grade, only list courses relevant to the major)

**Comment by ZzRanger** [comment]
Email & password reset (gets it's own section)

**Comment by ZzRanger** [comment]
What are the pros & cons for creating a user settings section vs having a profile section include user settings?

**Comment by ZzRanger** [comment]
**Steps to Implement**
Product
1. Discuss the need of such a screen
 - specifically, please make an argument for why user settings should be separate from profile
2. If we establish need, brainstorm a list of fields to include in user settings
3. Describe how the user should interact with user settings. Best would be to find functionality from an existing website as an example. For example, will we have it autosave, use a single "Confirm" button, etc.

Design
1. Create screen/s for user settings based on the functionality enumerated above.
2. Get feedback from product & project lead

Engineering
1. Implement user settings functionality
2. Open PR & get engineering approval
3. Get product & design approval
4. Merge!

**Comment by ZzRanger** [comment]
We can prolly address this at a later date
