### ISSUE TITLE
[Feature Request] Onboarding Flow

### ISSUE THREAD

**Issue by ChaoShaoBaoo** [UTDNebula/planner#236]
# Overview
Have a onboarding page/window for new users in order to welcome to Nebula

User should have a simple, quick welcome to website.

# Proposal
 1. First time users see: "Welcome, Student" and tutorial to inform them of how the website works (+ have "skip tutorial" button).
 2. Direct to Profile page in order to ask for "Email" (required to create profile). "Major, Minor, Honors, etc." are skippable for now.
- Email is used for profile log-in + if need to inform of session/date/time change for projected schedule.

## Supplementary Information
See [Cornell's](https://courseplan.io/login) for inspiration (simple, linear, marketable).

**Comment by ZzRanger** [comment]
Good work! We already have an onboarding flow which can be found [here](https://nebula-planner-bzy42yqqy-utdnebula.vercel.app/). However, it can definitely be improved upon. I really like the idea of adding a tutorial.

**Comment by ZzRanger** [comment]
**Steps to Implement**

Product
1. Create a user flow for onboarding flow
2. Write out what the tutorial should look like (i.e. what screens should it show, what features should it highlight, what should the user see)
3. Write out what the user flow should look like. Try to make this as detailed as possible for design & engineering team.

Design
1. Meet w/ product to understand new onboarding flow
2. Create mockups
3. Get feedback from product & project lead
4. Attach mockups to onboarding flow issue

Engineering
1.  Meet w/ product to understand feature
2. Implement feature
3. Open PR & get feedback from product & design team
4. Get feedback from project lead
5. Merge PR

**Comment by innub** [comment]
Hey, can I be assigned to this.
