### ISSUE TITLE
[Redesign] Change degree planning toolbar color

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#240]
Make toolbar in this screenshot same as buttons on home page. Toolbar can be found in [...planId.tsx]

<img width="1440" alt="Screen Shot 2022-10-13 at 4 50 09 PM" src="https://user-images.githubusercontent.com/47403443/196058008-9471e75d-ecc6-405b-9e71-f7197980f1dc.png">

**Comment by ReaverRage** [comment]
Is this what you're after?

![image](https://user-images.githubusercontent.com/95723769/198690327-bb147d7c-e2e8-4ed6-9fff-e9450523bf08.png)

**Comment by ZzRanger** [comment]
Yes that's perfect!
