### ISSUE TITLE
Sign Up invalid email prompt shouldn't be a popup [Redesign]

### ISSUE THREAD

**Issue by MichaelDHellman** [UTDNebula/planner#269]
# Background

Currently if an invalid email address is submitted the the signup page a browser popup is used to notify the user that they have given an invalid email address. This seems like a rather clunky solution.

# Proposal

Replace the popup with an item in the DOM which informs the user that they input an invalid email address.

**Comment by ZzRanger** [comment]
Something like this would be nice

**Comment by akevinge** [comment]
Implemented.
