### ISSUE TITLE
[Feature Request] Display degree plans in PDF format

### ISSUE THREAD

**Issue by WillieCubed** [UTDNebula/planner#29]
## Problem Description
Comet Planning will allow students an interactive means of planning out their coursework, but it may be useful to have a static representation of a student's academic career for easy reference.

## Proposed Problem Solution
Comet Planning will have a way to generate printable PDFs of the following:
- [ ] Planned/transferred/taken courses per semester
- [ ] Student course records (all attempted courses and their grades)

Essentially, Comet Planning will generate transcripts and customized degree plans for students based on the data they provide. There will be a dedicated route on the Comet Planning web app (`/schedules/<id>/view`) that will allow a student to see a (togglable) static visual representation of a degree plan or transcript-like view of all their attempted courses.

## Alternative Solutions
Another format that Comet Planning could explore is a spreadsheet containing the above information. However, implementation of this may largely depend on student feedback and demand. One possible compliment to the generated PDFs is to have the ability to share a schedule through a URL which would work with Comet Planning's existing routing solution; however, this would require implementation of some kind of permissions system - whether marking a schedule as public/private or by some other mechanism - which may not be desirable from a practicality standpoint.

## Additional Context
[Here](https://www.figma.com/file/VKW4sM9bQMvoBTrChlR2Il/Comet-Planning?node-id=24704%3A29478) is a reference to a viewing screen for a student's degree plan.

**Comment by wbne** [comment]
Here is the current status of the pdf using react-pdf: 
![image](https://user-images.githubusercontent.com/17793597/125215157-2b97ec00-e280-11eb-9a9f-757e70f9e63d.png)

Before I try to test out the download and stream feature I wanted to get feedback (besides the white highlight because it looked fine on my second screen).

**Comment by JCGarzaa** [comment]
Hi. I'll work on this.
