### ISSUE TITLE
[Feature Request] Support user-sign in to save data

### ISSUE THREAD

**Issue by WillieCubed** [UTDNebula/planner#30]
## Problem Description
Currently, schedule data is only persisted locally. However, there are use cases where a user may desire to have their data synced to a remote location:
- Modifying schedule data from another device, whether laptop or mobile
- Having data backed up in the event of hardware failure
- Using Comet Planning in Incognito Mode/private browsing mode

## Proposed Problem Solution
The following data would be stored in the Comet Planning Cloud Firestore database:
- Student metadata (including but not limited to current GPA, selected major(s)/minors, and course attempts)
- Student schedule data (all the schedules belonging to a student)

As this is an ACM Development project, Comet Planning will be using [ACM's Auth0 setup](https://github.com/acmutd/Auth-flow-template) to easily implement sign-in. 

## Alternative Solutions
The other option for synchronizing user data across devices is to focus on using a purely file-based system for saving data, but doesn't have the ease of use as a solution built into the app. As such, file-based save data will be complementary to the primary sign-in method of synchronizing data.

## Additional Context
Eventually, some Comet Planning data may be retrieved/shared from ACM's member database, but that is not a goal for this initial auth implementation.

**Comment by ZzRanger** [comment]
Resolved in 3d5696
