### ISSUE TITLE
[Redesign] Odd Button Spacing on Certain Platforms + Wording

### ISSUE THREAD

**Issue by ChaoShaoBaoo** [UTDNebula/planner#311]
# Context
Friend with Lenovo checked out Planner; buttons looked weird.
![image](https://user-images.githubusercontent.com/115287771/202057909-8af2927c-8868-4321-9789-b7de4d19d1d0.png)

*See "Report a bug," "Learn more." Later found that "Validate, Export, and Import" buttons were also squished.

# Wording
Friend also took the time to read the Disclaimer (i know, he's something else): it says something like "do not make any warranties..." and it sounds weird. Is it supposed to say something like "guarantees"? If "warranties" is correct, ignore this.

**Comment by ZzRanger** [comment]
Waiting for transcript to be fixed & design to make a better looking design.
