### ISSUE TITLE
[Feature Request] Honors Configuration

### ISSUE THREAD

**Issue by ChaoShaoBaoo** [UTDNebula/planner#312]
# Background

In the earlier unreleased version, we had a space for FastTrack, future plans, and an honors designation. However, beta does not include this honors section.

# Overview

The honors population at UTD is significant, and their requirements/goals for using Nebula may differ slightly from non-honors users. Listed some off top of my head below:

1. Using Nebula to determine their fulfillment of Proper/Advanced Hours
2. Mapping out the omission of a semester to study abroad/other programs offered in CV (e.g. Archer)
3. Minimum hours per semester (e.g. NM/CS^2 req. 15 hour minimum vs. 12 minimum for normal full-time UTD definition). 

# Proposal
Pt 1
Include an honors designation upon onboarding (specification of which honors is not as relevant for now; in the future can look to shape/recommend plans based on particular honors programs sure, but not now). This way, honors reading courses + honor proper/advanced hours (+ honor section professors, if we want to get into that level of specificity) can be accessible solely to honors users vs. potentially confuse non-honors users.

Implementation: In on-boarding, could simply be a Yes/No question (or list w/ different honors specifications in the future) declaring, "Are you a CollegiumV member?" [Drop down: Yes ; No].

Pt 2
Option 1. Have an "Honors Hours" counter. Either cumulative on a total "4-yr plan requirements post-it-note" type section on the screen. Would be another drop down on Post-It Requirements (potential courses would ideally be prioritized by relevance to major plan) #313 . 

OR 

Option 2. Assuming the student chose the Honors designation upon on-boarding, with each semester, spatially left to the # of total semester credit hours (SCH) they took, can there be a green/contrasting label of "X Honors Hrs." Which will not show by default; only when an honors course is recognized within the semester.

## Supplementary Information
Additionally, most of these honors students will have credits coming in, so the current templates may also be excessive and energetically unattractive to them since they'll have to reconfigure them to their personal needs, which almost entirely nullifies the value of using a template in the first place. I'll provide a proposal for another template format in a future issue.

**Comment by ZzRanger** [comment]
Good idea; will revisit at a later date!
