### ISSUE TITLE
[Bug]: Only First Four Courses on Semester Tile are Shown

### ISSUE THREAD

**Issue by thekevinge** [UTDNebula/planner#333]
### What did you expect to happen?

Users should be able to add more than 4 courses to a semester and still see them.

### What happened?

When adding five or more courses, the 5th+ courses are not visible.

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ZzRanger** [comment]
![Jan-25-2023 17-09-50](https://user-images.githubusercontent.com/47403443/214712614-b8cb326e-2c3b-4120-86c4-c63f24d67707.gif)
