### ISSUE TITLE
[Feature Request] Make Generic Button

### ISSUE THREAD

**Issue by thekevinge** [UTDNebula/planner#343]
## Overview
Make a generic button component that is used for all buttons in our app. 

### Implementation
- We sort of have a button type, which is in ``src/components/credits/Button.tsx``.  
- Make the new one in ``src/components/Button.tsx``.
- Here's an idea of what it could look like: https://github.com/benawad/dogehouse/blob/staging/kibbeh/src/ui/Button.tsx

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by ZzRanger** [comment]
Go for it!

**Comment by ZzRanger** [comment]
Close because #411
