### ISSUE TITLE
[🐛 Bug]: Discord provider doesn't load properly when running the production build locally

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#348]
### What did you expect to happen?

<img width="1438" alt="Screenshot 2023-01-28 at 12 01 36 PM" src="https://user-images.githubusercontent.com/47403443/215283392-51595d73-1e85-4b5e-b755-908397a94673.png">

### What happened?

![discord-weird](https://user-images.githubusercontent.com/47403443/215283475-a324fb9f-540d-45c5-82bc-a9838f2feb83.gif)

The Discord Provider is **known** to not work on preview deployments because it requires static callback/redirect urls. You can find more information about it [here](https://next-auth.js.org/deployment#securing-a-preview-deployment). However, it should work on local builds. 

_Note: A potential solution for preview could be somehow mapping the VERCEL_URL to NEXTAUTH_URL._

It works on Vercel when `NEXTAUTH_URL` is specified to the specific URL. (i.e. https://dev.planner.utdnebula.com/)

Relevant env variables: 
NEXTAUTH_URL=http://localhost:3000

**STEPS TO REPRODUCE**
1. npm run build && npm start

### Version

Beta 0.1.0

### Relevant log output

```shell
(node:43242) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.processResponse (node:internal/deps/undici/undici:5536:34)\n' +
      '    at node:internal/deps/undici/undici:5858:42\n' +
      '    at node:internal/process/task_queues:140:7\n' +
      '    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)\n' +
      '    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://localhost:3000/api/auth/csrf',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.processResponse (node:internal/deps/undici/undici:5536:34)\n' +
      '    at node:internal/deps/undici/undici:5858:42\n' +
      '    at node:internal/process/task_queues:140:7\n' +
      '    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)\n' +
      '    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://localhost:3000/api/auth/providers',
  message: 'fetch failed'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akevinge** [comment]
Slightly different solution but moved to https://nebula-labs.atlassian.net/browse/NP-97.
