### ISSUE TITLE
[🐛 Bug]: Get Started button doesn't work

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#349]
### What did you expect to happen?

"Get started" should redirect to /auth/login for now.

### What happened?

<img width="1440" alt="Screenshot 2023-01-28 at 7 39 53 PM" src="https://user-images.githubusercontent.com/47403443/215299384-1322a256-f432-40e9-b997-b1e241a7392e.png">

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav1707** [comment]
It is working well I see
