### ISSUE TITLE
[🐛 Bug]: Hide Email Provider Button

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#350]
### What did you expect to happen?

<img width="1440" alt="Screenshot 2023-01-28 at 7 40 57 PM" src="https://user-images.githubusercontent.com/47403443/215299449-3f8e8e92-e936-46dd-a1b9-2f93cc71c05a.png">

That button shouldn't exist

### What happened?

The button above exists

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rishav1707** [comment]
> ### What did you expect to happen?
> <img alt="Screenshot 2023-01-28 at 7 40 57 PM" width="1440" src="https://user-images.githubusercontent.com/47403443/215299449-3f8e8e92-e936-46dd-a1b9-2f93cc71c05a.png">
> 
> That button shouldn't exist
> 
> ### What happened?
> The button above exists
> 
> ### Version
> Beta 0.1.0
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

![sign in](https://user-images.githubusercontent.com/97666287/215309228-de252cc5-4f5f-466c-928c-6e3c183a4349.png)

I am not able to see any `sign in with Email` option
