### ISSUE TITLE
[Feature Request] Add ability to change plan title

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#361]
Currently there is no way to change a semester title. Additionally, the title displayed is NOT synced with title in DB.

<img width="1440" alt="Screenshot 2023-01-30 at 9 20 41 AM" src="https://user-images.githubusercontent.com/47403443/215518063-566baeb6-95d0-4ad4-9462-c654c83abc2a.png">

Note: THIS WILL BE WORKED ON AS AN ONBOARDING TASK DURING THE UPCOMING PLANNER MEETING. DO NOT WORK ON THIS, YOUR PR WILL BE CLOSED

**Comment by itsozair11** [comment]
Hello
