### ISSUE TITLE
[Feature Request] Implement Toast Notifications

### ISSUE THREAD

**Issue by thekevinge** [UTDNebula/planner#366]
## Overview

Implement a toast notification system for the entire app. 

### What are Toasts? 
This is just a notification that tells the user an action has successfully occurred or an error happened (eg. upon dragging a course to a semester: "CS 1200 Added To Fall 2023").
![](https://fireship.io/lessons/angular-toast-message-notifications-from-scratch/img/toast.gif)

### Related Files: 
- How the main Planner wrapper uses toasts: 
  https://github.com/UTDNebula/planner/blob/ad1f458943312448ec4fbc9b240dd154f0462b2e/src/components/planner/Planner.tsx#L129-L136
- ToastMessage type:
  https://github.com/UTDNebula/planner/blob/ad1f458943312448ec4fbc9b240dd154f0462b2e/src/components/planner/types.ts#L82-L86
- How toast messages are returned by async functions:
  https://github.com/UTDNebula/planner/blob/ad1f458943312448ec4fbc9b240dd154f0462b2e/src/pages/app/plans/%5BplanId%5D.tsx#L171-L174
  https://github.com/UTDNebula/planner/blob/ad1f458943312448ec4fbc9b240dd154f0462b2e/src/pages/app/plans/%5BplanId%5D.tsx#L193-L197

## Extra Info
- This could be implemented in the form of a React context + queue (do whatever works) and a notification component
- Make sure the notification always displays above other content
- For now, don't worry about its location on screen
- Focus on using the notification system in the only the ``src/components/planner/Planner.tsx`` component for now

<br>
This is a fairly sizeable issue. Feel free to ask if you have any questions :heart:

**Comment by sarthak22gaur** [comment]
Implementing the toast from scratch will be a lot of work with context, animations and what not :worried: 
We could use [react-toastify](https://www.npmjs.com/package/react-toastify) :upside_down_face: 

lmk your thoughts on this and I'll start working on it whichever way we decide with.

**Comment by ZzRanger** [comment]
Looked at it seems easy to integrate & style so I'm down to use that. Anyone else have thoughts?

**Comment by sarthak22gaur** [comment]
I'll start working with react-toastify and see how well it integrates. If it doesn't, then I'll write my own

**Comment by thekevinge** [comment]
Sounds good to me. Go for it
