### ISSUE TITLE
[🐛 Bug]: Error When Clicking To Remove Course Too Fast Too Many Times

### ISSUE THREAD

**Issue by thekevinge** [UTDNebula/planner#381]
## Overview
Clicking the 'X' to remove course from semester too fast too many times causes the following runtime error:
```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

## How to Reproduce
- Add a bunch of courses to a semester
- Spam the 'X' button as fast as possible

## Solutions
- Add a limiter to onClick (eg. 2 click in 5 seconds causes a following onClick to be ignored)
- Don't add delay on all onClick's. It would make the state updates janky.

**Comment by ZzRanger** [comment]
Method for removing courses different now
