### ISSUE TITLE
[Feature Request] Add Input Validation for Semesters in Profile

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#395]
Show a warning for the following cases:

1. User selects a starting semester that is before the ending semester.
2. Warn people if they change starting semester & they have credits that are earlier. For example, if in course history I have a course that's from F21, show an error if the user tries to set their starting semester to like S20. 

Maybe do something like this to show invalid field when they click the button:

![image](https://user-images.githubusercontent.com/47403443/220821570-815ba6b8-a4c4-4124-b9fe-7e3cc6a319ce.png)

**Comment by Peytonbarre** [comment]
I could take this
