### ISSUE TITLE
[Feature Request] Create user profile page

### ISSUE THREAD

**Issue by rajmeet2001** [UTDNebula/planner#40]
# Overview
The profile page provides options to the user to customize and make Nebula their own. The goal of this page is not to overwhelm the user with options that confuse them but as a way to help them modify the settings they want. Keeping consistency with every sub-page of the Profile would promote a better user experience. 

# Proposal

The Profile Page would include the following sections:

- Toggles for analytics
- Name change option
- Display options

## Supplementary Information
Find the link to the framework here https://www.figma.com/file/L56XKTwX0gml7vqQWdduBz/Profile-Page?node-id=0%3A1

**Comment by WillieCubed** [comment]
Hey Rajmeet, it appears the Figma file you've provided isn't publicly accessible. Could you update its permissions?

**Comment by rajmeet2001** [comment]
The link should be active.
