### ISSUE TITLE
Bug: Auth Slow 

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#402]
## Bug description

It takes a long time to load the /auth/login page. However, this only happens the first time you load the /auth/login page. Below are the relevant screenshots from devtools. 
 
<img width="1440" alt="Screenshot 2023-02-06 at 9 07 58 AM" src="https://user-images.githubusercontent.com/47403443/217008404-080b8605-6024-4e3d-8759-748312f31ec7.png">
<img width="1440" alt="Screenshot 2023-02-06 at 9 07 53 AM" src="https://user-images.githubusercontent.com/47403443/217008409-77f87e10-2409-43be-ab68-6cdb6efda366.png">

My assumption is that since we're [server side rendering](https://github.com/vercel/next.js/discussions/21836) the page, we're just experiencing cold start. This probably warrants further investigation 

**Potential Ideas + Resources**
1. Maybe we can try [caching](https://vercel.com/docs/concepts/functions/serverless-functions/edge-caching) the responses?
2. [This](https://github.com/vercel/next.js/discussions/38012?sort=new) and [this](https://github.com/vercel/vercel/issues/6292) might have useful info

**More Problems**

Haven't looked into this myself, but apparently auth is slow on off-campus wifi + email sign in doesn't work w/ Yahoo? Will break into separate issues later.

## Steps To Reproduce

1. Go to any preview deployment
4. Click "Get Started" or "Login" for the first time

## The expected behavior

It shouldn't be this slow lol.

**Comment by sarthak22gaur** [comment]
The most probable explanation
- cold start + instantiating the DB client and setting up connection + setting up auth providers + checking for the session
- No connection pooling (unless MongoDB does it by default, need to check this)

**Comment by jasonappah** [comment]
I would agree w/ Sarthak here. Going to drop these metrics from Atlas in here, notice the spike in database connections...  
![Untitled](https://user-images.githubusercontent.com/30608521/217089500-45c72aba-743d-4e45-96f9-494e4e837707.jpg)

**Comment by ZzRanger** [comment]
Addressed in #415
