### ISSUE TITLE
[Redesign] Make the button work across the area instead of just the arrow

### ISSUE THREAD

**Issue by lokeshyerneni** [UTDNebula/planner#406]
When clicking on the button (look at the attached image) to determine what courses satisfy the requirement, the user is forced to click on the arrow instead of just the area. 

Redesign the button where if any part of the area is clicked, then the user is able to go look at the courses that satisfy the respective requirement

![image](https://user-images.githubusercontent.com/31449837/218011634-c736c253-a4a0-4541-a974-bb712c99bb09.png)

**Comment by saidarsht** [comment]
Will work on it this weekend!
