### ISSUE TITLE
[Feature Request] Add Toast Notification to Updating Profile

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#421]
# Proposal

Add this toast but for updating profile. Have a toast for if it's successful and another toast for if it fails.

<img width="1440" alt="Screenshot 2023-02-22 at 10 18 05 PM" src="https://user-images.githubusercontent.com/47403443/220820426-6c7065e5-839a-4ffb-a5f1-93f5a4b9d71f.png">

See `SelectedCoursesToast.tsx` in `src/components/planner/SelectedCoursesToast.tsx` for an example.

**Comment by Peytonbarre** [comment]
I could take this:)
