### ISSUE TITLE
Bug: Changing Colors Doesn't Work on Firefox

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#439]
![Feb-26-2023 18-17-36](https://user-images.githubusercontent.com/47403443/221446451-0f461c23-a40e-4a89-83f3-186752150335.gif)

**Comment by jasonappah** [comment]
new issue 💀 changing colors works as of #442, but the tag still doesn't get displayed. see https://media.discordapp.net/attachments/1067936519152730203/1079575209104920606/Feb-26-2023_19-25-38.gif
