### ISSUE TITLE
[Feature Request] Make New Sign-in page

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#443]
Should look like [this](https://www.figma.com/file/SkHgv71h5ZeGGGYppIdX0q/Planner-Mockups%3A-V-1?node-id=726%3A16394&t=TOecNxL8E6Cb17f9-0)

**Comment by sudoer777** [comment]
FYI on the current login screen, if you spam click the sign in button when signing up, the user will get too many verification emails.
