### ISSUE TITLE
Bug: Change Search Icon Color

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#444]
## Bug description

Make the "Search Icon" button the same color as the Back button.

<img width="1440" alt="Screenshot 2023-02-26 at 10 21 55 PM" src="https://user-images.githubusercontent.com/47403443/221473652-df0a8b5f-264e-4502-8dcb-9cbe878e8311.png">

**Comment by Yashdon999** [comment]
I Would like to work on this issues

**Comment by Yashdon999** [comment]
hi sir this error is showing 
on Sign in page


.. This Error
Server Error
Error: Invalid environment variables

**Comment by Yashdon999** [comment]
![Screenshot from 2023-03-01 00-35-47](https://user-images.githubusercontent.com/104668751/221954532-88a6172e-d059-455f-accb-ff4ca97dc590.png)

**Comment by Yashdon999** [comment]
can you please fix the Error

**Comment by ZzRanger** [comment]
Can you take a look at your env variables? The error says they aren't set up correctly.
