### ISSUE TITLE
[Redesign] Figure out bypass UI

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#450]
<img width="1440" alt="Screenshot 2023-02-27 at 2 03 10 PM" src="https://user-images.githubusercontent.com/47403443/221670933-408ac9ad-7745-45b3-80d1-63bcb21e1a17.png">

Currently, bypass logic is handled on the RequirementGroup level. The method of overriding courses is done at the bottom. We can probably design this better.

**Comment by akevinge** [comment]
Moved to https://nebula-labs.atlassian.net/browse/NP-102.
