### ISSUE TITLE
[Internal] Secure tRPC Procedures

### ISSUE THREAD

**Issue by jasonappah** [UTDNebula/planner#471]
# Overview of Proposed Changes

What needs to change? Why should these changes be made?

Right now, users can call any protected procedure as long as they are authenticated, meaning someone with bad intentions could theoretically mess with other people's plans or user info. We should add checks to all of the protected procedures to ensure that the currently authenticated user is actually allowed to update a given resource before continuing with the request.

# Details

Go over what parts of the codebase need refactoring.

- [ ] Module 1
- [ ] Module 2
- [ ] etc.

**Comment by sarthak22gaur** [comment]
I put checks for this in the initial procedures. But it was implemented per procedure.
The better way would be to add middleware and that would require some changes to all procedures in terms of query inputs.

**Comment by akevinge** [comment]
Implemented.
