### ISSUE TITLE
[Redesign] Tab titles should be updated

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/planner#523]
# Background

Currently, the title of the browser tabs for Planner appear to be outdated or non-descriptive of the actual page content. On the home page, the tab shows as "planner.", and the login and onboarding pages show as "Nebula Web", for example. I have not thoroughly checked the entire app at this time.

<img width="330" alt="Screenshot 2023-03-22 at 5 51 30 PM" src="https://user-images.githubusercontent.com/13911970/227055981-536a6bce-cf03-4563-8749-de59618d0e21.png">

# Proposal

The entire app should be audited to ensure an appropriate tab title is being used on all pages. As long as some consistent pattern is used, it should look nice. One solution could be "Login - Planner" or similar. Even just setting to always be "Planner" would look better.

This change should be trivial from an implementation standpoint.

## Supplementary Information
N/A

**Comment by ZzRanger** [comment]
That's a good catch! We also need to change the logo haha

**Comment by Jake3231** [comment]
@cubetastic33 Is this closed by #550?

**Comment by cubetastic33** [comment]
@Jake3231 oh yeah it is. I guess 'resolves' is not a closing keyword haha
