### ISSUE TITLE
[Redesign] Create menu for landing page on mobile

### ISSUE THREAD

**Issue by cubetastic33** [UTDNebula/planner#530]
Clicking the menu icon in the landing page on mobile currently does nothing, it needs to open up a menu with the same options that the nav bar has on larger screens.

![Screen Shot 2023-03-23 at 18 19 08](https://user-images.githubusercontent.com/33519300/227385501-fc03459b-2793-46db-9777-27d8297e68bc.png)

**Comment by akevinge** [comment]
I think this was solved by removing the menu. The "Get Started" button is good enough for people to log in? Feel free to reopen on Jira though.
