### ISSUE TITLE
[Internal] Update Contact Information

### ISSUE THREAD

**Issue by CharlieMahana** [UTDNebula/planner#63]
# Overview of Proposed Changes
There are some issues throughout the repo where we reference [nebula.acmutd.co](https://nebula.acmutd.co), the ACM discord server, and the nebula-maintainers@acmutd.co email among other things. Please examine the codebase for all locations where we reference outdated information and update it.

# Details
Please update these outdated values among others you may notice:
- nebula-maintainers@acmutd.co -> core-maintainers@utdnebula.com
- `@acmutd/nebula-maintainers` -> `@UTDNebula/planner`
- https://github.com/acmutd/nebula-web.git -> https://github.com/UTDNebula/planner.git

# Implementation
Please prioritize updating documentation files such as README and CONTRIBUTING as soon as possible. Afterwards, update the other files such as the terms webpage.

**Comment by ZzRanger** [comment]
We also need to update the contributor's guide link. It is currently "https://nebula.acmutd.co".
