### ISSUE TITLE
[Bug]: Adding past semesters to degree plan

### ISSUE THREAD

**Issue by michellekelman** [UTDNebula/planner#70]
### What did you expect to happen?

I expected to be able to add past semesters after creating a new degree plan.

### What happened?

Adding a new semester begins with Fall 2021.

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZzRanger** [comment]
Thank you for pointing this out. The original intention was to only allow adding future semesters, but adding past semesters makes sense especially for those who already have a lot of credits already. 

For Planner v1, we plan to have a place for users to enter courses they've already taken to Planner. We can then add an option in the degree planner tool to display past semesters with all prior courses taken.
