### ISSUE TITLE
[Bug] Fix Add & Remove Semester Buttons

### ISSUE THREAD

**Issue by ZzRanger** [UTDNebula/planner#84]
### What did you expect to happen?

<img width="486" alt="Screen Shot 2022-02-07 at 3 25 46 PM" src="https://user-images.githubusercontent.com/47403443/152874531-1ab952ff-8525-4418-a9c1-9e462486d2c1.png">

### What happened?

I expect to see the '+' and the '-' on the buttons as shown in the image below.
<img width="475" alt="Screen Shot 2022-02-07 at 3 26 34 PM" src="https://user-images.githubusercontent.com/47403443/152874646-ada86293-9e48-4f15-8ceb-e0e9823b6d6a.png">

### Version

Beta 0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lokeshyerneni** [comment]
I will do it
