### ISSUE TITLE
[Feature Request] Auto-suggest adding lab sections when adding courses to degree plan

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/planner#97]
# Overview

I’ve been using Planner to lay out my real past courses, and I’ve run into an opportunity to improve the speed and usability of doing this. For example, if I add PHYS2325 to a semester, then it would be great if it suggested I add PHYS2125 to the same semester, since they’re required to be taken together. This seems like it could be a fairly easy to way to streamline the process.

# Proposal
In order to achieve this, it would be necessary to know corequisite requirements for all courses. Given this, presumably it would be fairly trivial to check to see if a course’s corequisites are present in a semester at the time a course is added to the degree plan. If not, some sort of UI could be shown to ask the user if they want to automatically add the lab/problem section. This could simply be a pop-up, or maybe an inline “template” course as shown in the attached rough sketch.

## Supplementary Information

Attached is one idea of how this UI could function.
![IMG_0258](https://user-images.githubusercontent.com/13911970/154754548-960567b8-0a0c-4fa9-b4a8-a5f540e76d50.jpeg)

**Comment by NoWhere-2-Go** [comment]
I would like to work on this issue
