### ISSUE TITLE
"ACM Development" should be "Project Nebula Maintainers" in footer

### ISSUE THREAD

**Issue by Jake3231** [UTDNebula/planner#99]
### What did you expect to happen?

On the Planner landing page, the footer should not incorrectly reference "ACM Development".

### What happened?

The landing page footer currently says, "Built with ❤️ and 💻 by ACM Development".

### Version

Beta 0.1.0

### What browsers are you seeing the problem on?

Safari

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WillieCubed** [comment]
Actually, let's change ACM Engineering to "Project Nebula Maintainers" instead.

**Comment by nsx00** [comment]
Hey I'm interested in the issue, can you assign it to me?
